# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=77)),
                ('nick_name', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('phone_number', models.CharField(max_length=20)),
                ('alipay_id', models.CharField(max_length=50)),
                ('balance_unfixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.PositiveSmallIntegerField()),
                ('acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
