# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='HFT',
            field=models.CharField(default=b'xx', max_length=2),
        ),
    ]
