# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_match_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='results',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
