# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20160812_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballbill',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
